-- MySQL Script generated by MySQL Workbench
-- Mon Jun 11 00:50:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Escolhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolhas` (
  `idEscolhas` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEscolhas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Altura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Altura` (
  `idAltura` FLOAT NOT NULL,
  PRIMARY KEY (`idAltura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idade` (
  `idIdade` INT NOT NULL,
  PRIMARY KEY (`idIdade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peso` (
  `idPeso` INT NOT NULL,
  PRIMARY KEY (`idPeso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `idSexo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diabetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diabetes` (
  `idDiabetes` CHAR(1) NOT NULL,
  PRIMARY KEY (`idDiabetes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resultado` (
  `idResultado` FLOAT NOT NULL,
  `Escolhas_idEscolhas` VARCHAR(2) NOT NULL,
  `Altura_idAltura` FLOAT NOT NULL,
  `Idade_idIdade` INT NOT NULL,
  `Peso_idPeso` INT NOT NULL,
  `Sexo_idSexo` CHAR(1) NOT NULL,
  `Diabetes_idDiabetes` CHAR(1) NOT NULL,
  PRIMARY KEY (`idResultado`),
  INDEX `fk_Resultado_Escolhas_idx` (`Escolhas_idEscolhas` ASC),
  INDEX `fk_Resultado_Altura1_idx` (`Altura_idAltura` ASC),
  INDEX `fk_Resultado_Idade1_idx` (`Idade_idIdade` ASC),
  INDEX `fk_Resultado_Peso1_idx` (`Peso_idPeso` ASC),
  INDEX `fk_Resultado_Sexo1_idx` (`Sexo_idSexo` ASC),
  INDEX `fk_Resultado_Diabetes1_idx` (`Diabetes_idDiabetes` ASC),
  CONSTRAINT `fk_Resultado_Escolhas`
    FOREIGN KEY (`Escolhas_idEscolhas`)
    REFERENCES `mydb`.`Escolhas` (`idEscolhas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Altura1`
    FOREIGN KEY (`Altura_idAltura`)
    REFERENCES `mydb`.`Altura` (`idAltura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Idade1`
    FOREIGN KEY (`Idade_idIdade`)
    REFERENCES `mydb`.`Idade` (`idIdade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Peso1`
    FOREIGN KEY (`Peso_idPeso`)
    REFERENCES `mydb`.`Peso` (`idPeso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `mydb`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Diabetes1`
    FOREIGN KEY (`Diabetes_idDiabetes`)
    REFERENCES `mydb`.`Diabetes` (`idDiabetes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calculadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calculadora` (
  `idCalculadora` INT NOT NULL,
  `Altura` FLOAT NULL,
  `Escolhas` INT NULL,
  `Idade` INT NULL,
  `Peso` INT NULL,
  `Sexo` INT NULL,
  `Diabetes` INT NULL,
  `Resultado` DOUBLE NULL,
  PRIMARY KEY (`idCalculadora`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
